#ifndef RESOURCES_H
#define RESOURCES_H

#define MAIN_MENU_ID 1
#define THE_EDITOR_ICON_ID 1

#define CM_FILE_NEW 100
#define CM_FILE_OPEN 101
#define CM_FILE_SAVE 102
#define CM_FILE_SAVE_AS 103
#define CM_FILE_RELOAD 104
#define CM_FILE_PAGE_SETUP 105
#define CM_FILE_PRINT 106
#define CM_FILE_EXIT 107

#define CM_EDIT_UNDO 200
#define CM_EDIT_REDO 201
#define CM_EDIT_CUT 202
#define CM_EDIT_COPY 203
#define CM_EDIT_PASTE 204
#define CM_EDIT_DELETE 205
#define CM_EDIT_FIND 206
#define CM_EDIT_FIND_NEXT 207
#define CM_EDIT_REPLACE 208
#define CM_EDIT_GO_TO_LINE 209
#define CM_EDIT_SELECT_ALL 210

#define CM_VIEW_FONT 301
#define CM_VIEW_TAB_WIDTH 302
#define CM_VIEW_WORD_WRAP 303
#define CM_VIEW_VISIBLE_WHITE_SPACE 304
#define CM_VIEW_STATUS_BAR 305
#define CM_VIEW_LINE_NUMBERS 306

#define CM_HELP_VIEW_HELP 400
#define CM_HELP_ABOUT_THE_EDITOR 401

#endif
